# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(998, 750)
        Dialog.setStyleSheet("QPushButton {\n"
"    background-color: rgb(255, 0, 255);\n"
"background-color:white;\n"
"text-align:center;\n"
"}\n"
"QPushButton:hover{\n"
"background-color:silver\n"
"}\n"
"QPushButton:pressed{\n"
"}\n"
"QDialog{\n"
"    background-color: rgb(170, 85, 255);\n"
"}\n"
"")
        self.txt1 = QtWidgets.QLineEdit(Dialog)
        self.txt1.setGeometry(QtCore.QRect(140, 120, 741, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt1.setFont(font)
        self.txt1.setObjectName("txt1")
        self.push = QtWidgets.QPushButton(Dialog)
        self.push.setGeometry(QtCore.QRect(350, 370, 211, 71))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.push.setFont(font)
        self.push.setObjectName("push")
        self.txt3 = QtWidgets.QLineEdit(Dialog)
        self.txt3.setGeometry(QtCore.QRect(410, 230, 111, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.txt3.setFont(font)
        self.txt3.setObjectName("txt3")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(440, 490, 271, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(360, 490, 131, 131))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(380, 100, 281, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(440, 210, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.push.setText(_translate("Dialog", "Вычислить"))
        self.label_2.setText(_translate("Dialog", "Вывод:"))
        self.label_3.setText(_translate("Dialog", "Введите пример"))
        self.label_5.setText(_translate("Dialog", "MOD"))
